### ISSUE TITLE
Tickets display Bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#580]
On the ticket page, if i have only one ticket, it is displayed at the center of the page on the show all ticket page, instead of being aligned to the top-left corner of the screen.

![image](https://user-images.githubusercontent.com/27733432/130747008-68699291-c01c-4088-a0c1-522b2061f092.png)

Also, when i rename a wallet, this does not reflect on the tickets as it still displays the old wallet name.
![image](https://user-images.githubusercontent.com/27733432/130754236-60b64d6e-fb31-4c60-a16b-0e09a00630f9.png)

**Comment by oshorefueled** [comment]
This has been fixed on #458 you can test the PR to confirm.

**Comment by Sirmorrison** [comment]
Theses were not resolved.
Found theses bugs while testing from the PR.
I also left comments on the PR.

**Comment by oshorefueled** [comment]
Here's a page with one ticket and it displays correctly on #458 

<img width="674" alt="Screenshot 2021-08-27 at 15 55 35" src="https://user-images.githubusercontent.com/15804688/131147441-413d130f-9a29-430d-93e4-f17140a9db4f.png">
